Support multiple stratification CSV uploads
CarnegieLearningWeb/UpGrade pull request #1088
Opened 2023-10-27 19:16 UTC by zackcl

This change allows uploading multiple stratification CSV files at once.

https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/965a8f35-9d55-442c-8652-de39e8ee0781

I've uninstalled the `multer` library since the files are not being sent as actual file uploads. Instead, they're sent as plain text within the request body.

Please review the code.

2023-10-27 19:38 UTC, zackcl commented
@danoswaltCL Was our original plan to allow uploading only one CSV file at a time? (https://github.com/CarnegieLearningWeb/UpGrade/issues/966)

2023-10-27 19:40 UTC, danoswaltCL commented
I don't recall, could have been discussed at some point but I'm not sure it was something that was specifically asked for.

2023-10-29 07:11 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/controllers/StratificationController.ts
> +    const results: UserStratificationFactor[] = [];
Instead of `for` loop, you should use `Array.map` here

2023-10-29 07:12 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/controllers/StratificationController.ts
> +    if (!Array.isArray(uploadedFiles) || !uploadedFiles.every(item => typeof item.file === 'string')) {
This part can be done using class-validators.

2023-10-29 07:15 UTC, VivekFitkariwala requested changes
I don't see any change in the `package.json`. (The multer should be removed).

2023-10-30 23:00 UTC, zackcl commented
@VivekFitkariwala I'm not sure if this is the proper way to add a validator. I had to update the client request body structure in order to make this endpoint work. Please let me know if this is not correct, and also feel free to make changes to this PR. Thank you!

2023-11-01 14:33 UTC, zackcl commented
I'm closing this PR because it's a low priority and needs more time for review and testing.

The issue: https://github.com/CarnegieLearningWeb/UpGrade/issues/1094

2023-11-01 14:33 UTC, closed without merging