Excluding enrollmentComplete experiments from getValidExperiments query (#909)
CarnegieLearningWeb/UpGrade pull request #1095
Opened 2023-11-02 08:59 UTC by ppratikcr7

This PR contains changes to improve the PROD latency issues due to enrolmentComplete experiments for post-experiment rule set to default condition. We are now excluding enrollmentComplete experiments from getValidExperiments and getValidExperimentsWithPreview queries.

This gives an optimization of 62% in terms of average api response time for 600 concurrent users. With Splitting of queries into 3 and Caching, the time is reduced by 91% in terms of average api response time for 600 concurrent users. Please find the detailed Load Testing Analysis in this [document](https://docs.google.com/document/d/1hsQpcF3ptcYaHfUaw_iqPrCv0AK4hx4YVJrdfYclNlM/edit?usp=sharing). Here is the Response Time Comparison table:
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-a12e0a09-7fff-7017-ecb6-b4e70c70c1ba"><div dir="ltr" style="margin-left:0pt;" align="center">

Test Case | Concurrent Users | Trail 1 (Median Response Time) | Trail 2 (Median Response Time) | Avg of (Median Response Time)
-- | -- | -- | -- | --
No enrollmentComplete experiments (Total 8 experiments) | 600 | 5700 ms | 4300 ms | 5000 ms
All post-exp rule default experiments set to enrollmentComplete (5 out of 8 experiments) | 600 | 7300 ms | 7800 ms | 7500 ms
Exclude enrollmentComplete experiments from getValidExperiments(5 out of 8 experiments) | 600 | 3100 ms | 2600 ms | 2850 ms
Split queries into 3 + Exclude enrollmentComplete experiments from getValidExperiments(5 out of 8 experiments) | 600 | 2300 ms | 1800 ms | 2050 ms
Split queries into 3 + Caching + Exclude enrollmentComplete experiments from getValidExperiments(5 out of 8 experiments) | 600 | 850 ms | 550 ms | 700 ms
Split queries into 3 + Caching + Exclude enrollmentComplete experiments from getValidExperiments(5 out of 8 experiments) | 400 | 88 ms | 91 ms | 89.5 ms
Split queries into 3 + Caching + Exclude enrollmentComplete experiments from getValidExperiments(5 out of 8 experiments) | 200 | 30 ms | 37 ms | 33.5 ms

</div></b>

2023-11-02 16:24 UTC, danoswaltCL commented
👍 will look into tests with this after we have satisfied our testing with the caching fix

2023-11-02 16:26 UTC, ppratikcr7 commented
> 👍 will look into tests with this after we have satisfied our testing with the caching fix

Sure, just fixing a few test cases for this PR. Will push the commit soon.

2023-11-03 12:34 UTC, ppratikcr7 commented
> 👍 will look into tests with this after we have satisfied our testing with the caching fix
Need to push a fix in this PR, so moving the PR to draft.

2023-11-07 05:34 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/repositories/ExperimentRepository.ts
> +            '(experiment.state = :enrolling OR NOT (experiment.state = :enrollmentComplete AND experiment.postExperimentRule = :assign AND experiment.revertTo IS NULL)) AND :context ILIKE ANY (ARRAY[
This query will return inactive, preview and other experiments. It should be something like this
enrolling OR enrollmentComplete AND NOT (enrollmentComplete and postRule = assign and revertTo is NULL)
or 
enrolling OR (enrollmentComplete and revertTo is NOT NULL)

2023-11-07 05:37 UTC, VivekFitkariwala requested changes
There are a lot of repetitions of the text. You can make it a const.

2023-11-07 17:37 UTC, ppratikcr7 commented
@VivekFitkariwala @danoswaltCL Closing this PR, as opened a new [one](https://github.com/CarnegieLearningWeb/UpGrade/pull/1102) with a single cleaner commit with no test cases altered. Earlier I had altered test cases in PR which are not needed.

2023-11-07 17:37 UTC, closed without merging