Enhancement/1097 mark optimization
CarnegieLearningWeb/UpGrade pull request #1146
Opened 2023-11-22 06:35 UTC by RidhamShah

2023-11-23 07:03 UTC, ppratikcr7 commented on backend/packages/Upgrade/src/api/services/SegmentService.ts
> +      console.log('ids', ids);
remove this console log

2023-11-23 07:03 UTC, ppratikcr7 commented on backend/packages/Upgrade/src/api/services/SegmentService.ts
> +      console.log('sortedData', sortedData);
remove this console log

2023-11-28 07:12 UTC, VivekFitkariwala requested changes
Some small requested. PR looks good.

2023-11-28 07:12 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/services/ExperimentAssignmentService.ts
> +        const selectedExperimentDP = dpExperiments.filter((dp) => dp.experiment.id === experimentId);
Use find instead of filter

2023-11-29 06:29 UTC, RidhamShah commented on backend/packages/Upgrade/src/api/services/ExperimentAssignmentService.ts
> +        const selectedExperimentDP = dpExperiments.filter((dp) => dp.experiment.id === experimentId);
code updated

2023-11-29 13:25 UTC, VivekFitkariwala approved these changes

2023-11-29 15:04 UTC, merged