Readme enhancement
CarnegieLearningWeb/UpGrade pull request #1176
Opened 2023-12-08 14:04 UTC by ppratikcr7

This separate PR contains updated readme with dynamic badges and other details related to `Upgrade` to help reach more people. Please review and discuss if we need edit/add/remove anything.

2023-12-08 14:50 UTC, danoswaltCL commented
@amurphy-cl can you give us your thoughts on the new documentation? we're assigning you as code-reviewer for this one

2023-12-19 20:26 UTC, bcb37 requested changes
Just one nit. Otherwise it looks good, just need to resolve the merge conflicts.

2023-12-19 20:26 UTC, bcb37 commented on README.md
> +```
This NOTE text appears in a horizontal scroll, rather than wrapping. I think it probably doesn't need to be inside the ```'s.

2023-12-22 08:51 UTC, ppratikcr7 commented
@bcb37 Now the PR is ready for approval and merging.

2023-12-22 14:46 UTC, bcb37 approved these changes

2023-12-22 14:46 UTC, merged