Added sample responses in swagger. (such as 200, 404, 500)
CarnegieLearningWeb/UpGrade pull request #127
Opened 2021-08-25 10:47 UTC by YashilDepani

In this PR,  I have added sample responses for Experiment and Experiment-client APIs. These includes responses such as 200, 404, 500.

2021-09-02 05:50 UTC, RidhamShah commented
Things to change:

1. `/mark` - not working in swagger
2. `/log` - giving 500 errors 
3. `/bloblog` - something is going in infinite loop
4. `/failed` - not working
5. `/feature flag` - not showing data even if there is
6. `/condition{id}` - giving 500 error instead of 404 for wrong UUID

2021-09-07 11:04 UTC, YashilDepani commented
@msandbothe as we had a discussion regarding adding test cases for cases such as 500, 404, etc. I looked into the test cases and as we are mocking the services it is not possible to generate such cases. I have added a few possible test cases giving 500 errors when the ```experiment id is not of type UUID``` as this was checked before in the code and not related to service.

2021-09-08 08:51 UTC, RidhamShah requested changes
Things to change:

1. `/mark` - not working in swagger
2. `/log` - giving 500 errors
3. `/bloblog` - something is going in infinite loop
4. `/failed` - not working
5. `/feature flag` - not showing data even if there is
6. `/condition{id}` - giving 500 error instead of 404 for wrong UUID

2021-09-09 13:11 UTC, RidhamShah approved these changes

2021-09-15 17:55 UTC, merged