Storing proper group exclusion and individual exclusion documents
CarnegieLearningWeb/UpGrade pull request #1343
Opened 2024-03-06 09:00 UTC by ppratikcr7

This PR resolves #1318 

The `GROUP_ON_EXCLUSION_LIST` experiment level exclusion wont work due to experiment.group = null for within subject experiments.

Below are the changes done:
1. For a group experiment, a group Exclusion document should be created only if the experiment group is the same as the segment's group because of which the user got excluded
2. If a group (school1) was included earlier and we change the exclusion list and add group (school1), we should delete the group enrollment doc from the db table.
3. We should also store the Individual Exclusion doc as well with the Group Exclusion doc.
4. Code optimization for mark and assign call involving exclusions.

2024-03-11 05:28 UTC, VivekFitkariwala requested changes

2024-03-11 05:28 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/repositories/GroupEnrollmentRepository.ts
> +      .returning('*')
You can remove the returning part

2024-03-11 05:28 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/services/ExperimentAssignmentService.ts
> +        this.groupEnrollmentRepository.deleteGroupEnrollment(user?.workingGroup[experiment.group], new UpgradeLogger());
await here.
For multiple async requests happening here you should use `Promise.all`
Same thing below

2024-03-11 17:38 UTC, danoswaltCL commented
@VivekFitkariwala @ppratikcr7 is this one still waiting on changes? would like to merge this one into the parent branch before merging into that into the release branch so I only have to sync up one release/5.1 update.

2024-03-14 08:39 UTC, ppratikcr7 commented
> @VivekFitkariwala @ppratikcr7 is this one still waiting on changes? would like to merge this one into the parent branch before merging into that into the release branch so I only have to sync up one release/5.1 update.

The changes are done. Yeah if approved, we can merge this.

2024-03-14 10:01 UTC, VivekFitkariwala approved these changes

2024-03-15 15:24 UTC, merged