✨ Enhancement: Update data CSV export format
CarnegieLearningWeb/UpGrade pull request #1378
Opened 2024-03-19 09:03 UTC by ppratikcr7

This PR updates the data CSV export format as per this [format](https://docs.google.com/spreadsheets/d/1qAy7SNklPBWTtJed0Bqc8IppZn5DsQ4nBRsjtP-wtm0/edit?usp=sharing).

For the above format, we have updated the query to be build using `MonitoredDecisionPoint` table to capture all the mark calls. This will include both enrolled and excluded users data. 

For the excluded user's groupId data, we had to add a column `groupId` in the `IndividualExclusion` table similar to what we have in the `IndividualEnrollment` table.

2024-03-19 09:28 UTC, ppratikcr7 commented
@amurphy-cl In the above export format shared by you, do we need to store `na` in stratifications column for the user's whose stratification data is not available, or should we keep it blank in the export csv?

Also, you have kept `na` data in Payloads column, but now that we store default payload names in the DB, we wont have any such `na` values. Correct me if I am getting this wrong?

<img width="897" alt="Screenshot 2024-03-19 at 2 57 41 PM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/33730817/50b43464-69b2-439b-ab56-1026e9bc6aed">

2024-03-20 07:04 UTC, VivekFitkariwala requested changes

2024-03-20 07:04 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/services/ExperimentAssignmentService.ts
> +        groupId: user?.workingGroup[experiment.group],
`user?.workingGroup?.[experiment.group]` to make sure workingGroup is not null or defined. Same change below

2024-03-20 17:42 UTC, ppratikcr7 commented on backend/packages/Upgrade/src/api/repositories/AnalyticsRepository.ts
> +      .innerJoin(Experiment, 'experiment', 'experiment.id::text = "monitoredDecisionPoint"."experimentId"')
Yeah, the next step is this. I and Saumya would be looking into this query for optimization.

2024-03-26 05:54 UTC, VivekFitkariwala approved these changes

2024-04-01 20:33 UTC, merged