Remove unused relation in Experiment Assignment Service
CarnegieLearningWeb/UpGrade pull request #1525
Opened 2024-05-10 18:50 UTC by RidhamShah

Improve Monitored-Decision-Point query by removing unnecessory relations.

2024-05-10 18:52 UTC, RidhamShah commented
@danoswaltCL @bcb37 you can also test this change and push it in release 5.1

2024-05-12 09:45 UTC, VivekFitkariwala requested changes

2024-05-12 09:45 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/services/ExperimentAssignmentService.ts
>          user: userId,
The user here should be the original user instead of just the `userId`. Can you replace this code with
`user: userDoc`

2024-05-14 12:12 UTC, danoswaltCL commented
I tried load-testing this quickly a couple times and surprisingly didn't see improved performance. Still I think this only makes sense to merge anyway?

2024-05-14 12:13 UTC, danoswaltCL approved these changes

2024-05-14 12:38 UTC, danoswaltCL commented on backend/packages/Upgrade/src/api/services/ExperimentAssignmentService.ts
> +        user: userDoc,
It seems like userId should be faster if TypeORM just needs the Primary Key, right? It may not really matter one way or another, just curious.

2024-05-17 13:53 UTC, merged