Throw error when user not found in ExperimentController
CarnegieLearningWeb/UpGrade pull request #1692
Opened 2024-06-25 10:30 UTC by KD1712

2024-06-26 09:05 UTC, RidhamShah commented
This changes should be on all version of ExperimentClientController.

2024-06-26 09:16 UTC, RidhamShah requested changes

2024-06-26 09:16 UTC, RidhamShah commented on backend/packages/Upgrade/src/api/middlewares/UserCheckMiddleware.ts
> +      if (req.url !== '/api/init') {
There is no need to check userId from the header for the init call, so bring this if statement on the top.

2024-06-27 13:13 UTC, VivekFitkariwala commented
@bcb37 @danoswaltCL, At present we are fetching the user doc in each HTTP request of Experiment Client and that is redundant. In this PR is moving that in the middleware and the error will be thrown at the place where the document is fetched instead of the service which is incorrect.
We can have this middleware in the latest v5 version and not touch the service for backward compatibility.

2024-06-27 19:50 UTC, danoswaltCL commented
Another consideration is that this will break current non-client-library usage of the API, such as Livehint AI. They will need to begin sending this in the header for all calls.

2024-07-02 18:32 UTC, danoswaltCL commented
Let's wait on merging this in, see my comments in https://github.com/CarnegieLearningWeb/UpGrade/pull/1606

2024-07-07 20:06 UTC, VivekFitkariwala approved these changes

2024-08-09 13:44 UTC, danoswaltCL commented
holding off on this one, going with existing 404 errors in the individual endpoints still for now

2024-09-04 13:50 UTC, danoswaltCL commented
Needs to be only a part of the v6 controller. see: https://github.com/CarnegieLearningWeb/UpGrade/issues/1851 @ppratikcr7 @VivekFitkariwala

2024-09-16 08:43 UTC, ppratikcr7 commented
Closing this as its handled in a new [PR](https://github.com/CarnegieLearningWeb/UpGrade/pull/1955) with v6 client controller.

2024-09-16 08:43 UTC, closed without merging