feature flag lists backend changes
CarnegieLearningWeb/UpGrade pull request #1719
Opened 2024-07-02 19:51 UTC by bcb37

With these changes, the feature flag endpoints will not be used to perform CRUD operations on the inclusion and exclusion lists (with the exception of GET by :id, which will return the lists along with the other feature flag data)

Operations on the lists will be performed using the segments endpoints, which have three new optional attributes:
- enabled: boolean
- includedInFeatureFlag: FeatureFlag
- excludedFromFeatureFlag: FeatureFlag

Example body for flag creation (POST to /api/flags endpoint):
`{
    "name": "Test Flag",
    "key": "TEST_FLAG",
    "description": "Test Description",
    "status": "enabled",
    "context": [
        "assign-prog"
    ],
    "tags": [
        "tag99",
        "tag96"
    ],
    "filterMode": "includeAll"   
}`

Example body to add an inclusion list for the above (POST to /api/segments endpoint):
`{
    "name": "Included segments",
    "description": "desc",
    "context": "assign-prog",
    "userIds": [],
    "enabled": false,
    "groups": [],
    "subSegmentIds": ["f6a634b2-7ce4-4135-814f-520cb92fc9e0", "67de5a4a-3c5f-4dc3-a601-0b2e4deb213a"],
    "type": "private",
    "excludedFromFeatureFlag": "fee20c9b-2f5c-4bda-afb1-9f7434e5f89f"
}`

assuming the above UUIDs refer to entities that exist in the db.

2024-07-03 20:47 UTC, danoswaltCL commented
Ok, I'm working on the modals for adding/modifying a flag...we have slightly different constraints for add and modify requests that we can enforce with types, so would you say these are accurate representations of our types (FeatureFlag being the full document from the db that we should expect as a response?)

```
export interface AddFeatureFlagRequest {
  name: string;
  key: string;
  description?: string;
  context: string[];
  tags: string[];
}

export interface ModifyFeatureFlagRequest {
  name?: string;
  key?: string;
  description?: string;
  status?: FEATURE_FLAG_STATUS;
  filterMode?: FILTER_MODE;
  context?: string[];
  tags?: string[];
  enabled?: boolean;
}

export interface FeatureFlag {
  createdAt: string;
  updatedAt: string;
  versionNumber: number;
  id: string;
  name: string;
  key: string;
  description: string;
  status: FEATURE_FLAG_STATUS;
  filterMode: FILTER_MODE;
  context: string[];
  tags: string[];
  enabled: boolean;
}
```

2024-07-03 22:30 UTC, bcb37 commented
> Ok, I'm working on the modals for adding/modifying a flag...we have slightly different constraints for add and modify requests that we can enforce with types, so would you say these are accurate representations of our types (FeatureFlag being the full document from the db that we should expect as a response?)
> 
> ```
> export interface AddFeatureFlagRequest {
>   name: string;
>   key: string;
>   description?: string;
>   context: string[];
>   tags: string[];
> }
> 
> export interface ModifyFeatureFlagRequest {
>   name?: string;
>   key?: string;
>   description?: string;
>   status?: FEATURE_FLAG_STATUS;
>   filterMode?: FILTER_MODE;
>   context?: string[];
>   tags?: string[];
>   enabled?: boolean;
> }
> 
> export interface FeatureFlag {
>   createdAt: string;
>   updatedAt: string;
>   versionNumber: number;
>   id: string;
>   name: string;
>   key: string;
>   description: string;
>   status: FEATURE_FLAG_STATUS;
>   filterMode: FILTER_MODE;
>   context: string[];
>   tags: string[];
>   enabled: boolean;
> }
> ```

This looks correct, with the following exceptions:

- Add and Modify should be the same: they both should have 'context' and 'filterMode'
- Neither Add nor Modify should have 'enabled', which is not a thing (that's handled by 'status)
- The response from the GET endpoint for a single Feature Flag would also contain two arrays: 'featureFlagSegmentInclusion' and 'featureFlagSegmentExclusion', which would be arrays of private segments.

2024-07-07 20:03 UTC, VivekFitkariwala commented
@bcb37 I am not sure why you have deleted the junction table of `Feature Flag Segment Exclusion` and `Feature Flag Segment Exclusion`. Because of this, the relationship data is now moved into the Segment table. If you had added the enabled property in these junction tables and changed the OneToOne relationship to OneToMany in the Feature Flag table you could have achieved the same thing.

2024-07-08 19:13 UTC, bcb37 commented
> @bcb37 I am not sure why you have deleted the junction table of `Feature Flag Segment Exclusion` and `Feature Flag Segment Exclusion`. Because of this, the relationship data is now moved into the Segment table. If you had added the enabled property in these junction tables and changed the OneToOne relationship to OneToMany in the Feature Flag table you could have achieved the same thing.

I was thinking it's better to simplify the database and data models. We can now store the information we need with fewer moving parts, and query with fewer joins. And now we can manage the inclusions and exclusions from the front end just using the segment endpoints that already exist. Is there a compelling reason to use those junction tables for the relationships between feature flags and segments?

2024-07-09 13:21 UTC, VivekFitkariwala commented
@bcb37 this change is adding property which doesn't belong to Segment and that is the concern. I don't know if we are facing any issues because of this specific join.
Thinking ahead when we have to refactor the Experiment we will end up adding those specific data also in the Segment table. The present design of table is better I think.

2024-07-09 19:27 UTC, bcb37 commented
> @bcb37 this change is adding property which doesn't belong to Segment and that is the concern. I don't know if we are facing any issues because of this specific join. Thinking ahead when we have to refactor the Experiment we will end up adding those specific data also in the Segment table. The present design of table is better I think.

Ok, that makes sense to restore the junction tables. I think we'll still need new endpoints for editing the lists. They should be relatively similar to the /segment endpoints, with the addition of managing the junction table entries. Since we don't create feature flags initially with any exclusion or inclusion lists, I still think it makes sense to edit them separately.

2024-07-15 14:17 UTC, danoswaltCL commented
@VivekFitkariwala please consider this the highest priority review...

putting comments from dev sync in writing: it was suggested that `PUT api/flags/addInclusionList/:id` for edit may be preferred for the edit flow over `POST /api/flags/addInclusionList`.

also enums for the `listType` were discussed, but I think we landed on leaving it as is because group `listType` is not constant, comes from the context metadata.

Zack mentioned that it might be best API practice to only need to send changed fields when updating a known entity, but that is a larger architectural design change, currently we tend to always pass the entire document (correct me if this what was basically discussed)

2024-07-16 00:55 UTC, bcb37 commented
> @VivekFitkariwala please consider this the highest priority review...
> 
> putting comments from dev sync in writing: it was suggested that `PUT api/flags/addInclusionList/:id` for edit may be preferred for the edit flow over `POST /api/flags/addInclusionList`.
> 
> also enums for the `listType` were discussed, but I think we landed on leaving it as is because group `listType` is not constant, comes from the context metadata.
> 
> Zack mentioned that it might be best API practice to only need to send changed fields when updating a known entity, but that is a larger architectural design change, currently we tend to always pass the entire document (as was my understanding of that concern)

I spent all day making changes and updating the tests, but it doesn't look like those commits ended up on the branch. I'll try again tomorrow.

2024-07-16 06:49 UTC, VivekFitkariwala requested changes

2024-07-16 06:49 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/controllers/SegmentController.ts
> + *       enabled:
Do we need this?

2024-07-16 06:49 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/models/FeatureFlagSegmentExclusion.ts
> +  public listType: string;
We can use enum in the database but if we don't want that we should use string literals in the type.

2024-07-16 06:49 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/models/FeatureFlagSegmentExclusion.ts
> +  @Column()
We can add a default value as false.

2024-07-16 06:49 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/models/FeatureFlagSegmentInclusion.ts
> +
Same as in Segment Exclusion

2024-07-16 06:49 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/services/FeatureFlagService.ts
> +        featureFlag.featureFlagSegmentInclusion.forEach(async (segmentInclusion) => {
Do we need this? The cascade delete should automatically delete this.

2024-07-16 06:49 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/services/FeatureFlagService.ts
> +        featureFlag.featureFlagSegmentInclusion.forEach(async (segmentInclusion) => {
In that case the transaction is not required

2024-07-16 06:52 UTC, VivekFitkariwala commented
@danoswaltCL Sorry for the delay. I have added my review comments.

2024-07-16 18:53 UTC, bcb37 commented on backend/packages/Upgrade/src/api/controllers/FeatureFlagController.ts
> +    @Param('id') segmentId: string,
This seems to be how single UUID parameters are verified throughout the codebase. If we create a validator that checks whether something's a UUID, we should probably start using it everywhere. Maybe a separate task for that.

2024-07-18 09:00 UTC, VivekFitkariwala approved these changes

2024-07-18 14:04 UTC, merged