Issues in sending csv email and adding proper error codes and swagger improvements
CarnegieLearningWeb/UpGrade pull request #1735
Opened 2024-07-05 13:53 UTC by ppratikcr7

Adding proper error codes for sending email and error code coverage in analytics controller swagger doc.
There was an error of "Missing final '@domain'" due to a comma after the email id in env file. This PR resolves #1733 
<img width="639" alt="Screenshot 2024-07-05 at 6 52 17 PM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/33730817/bc828c56-d4fb-45e2-871f-a4343e1a527c">

2024-07-07 15:11 UTC, VivekFitkariwala requested changes

2024-07-07 15:11 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/services/AnalyticsService.ts
> +      try {
Try catch should only wrap `sendEmail` function

2024-07-22 14:52 UTC, danoswaltCL commented
@VivekFitkariwala can we get an updated review on this so we can move towards resolving some of our older PRs?

2024-07-22 15:02 UTC, VivekFitkariwala approved these changes

2024-07-22 19:50 UTC, merged