implement FF exposures for v1
CarnegieLearningWeb/UpGrade pull request #1865
Opened 2024-08-26 22:40 UTC by bcb37

- Add an exposure record in the exposures table every time the client gets feature flags for a user
- Display the number of exposures associated with a given feature flag on the list page 'Exposures' column

2024-08-27 11:53 UTC, VivekFitkariwala requested changes

2024-08-27 11:53 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/services/FeatureFlagService.ts
> +      await Promise.all(
Instead of using a `map` which will do multiple DB requests, you should use an array to save all the documents in a single request.

2024-08-27 11:53 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/services/FeatureFlagService.ts
> +      throw error;
Should we throw an error here or log the error and complete the request?
Saving the exposure is not a primary action, this HTTP request should succeed.

2024-08-27 11:53 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/services/FeatureFlagService.ts
> +      .leftJoinAndSelect('feature_flag.featureFlagExposures', 'featureFlagExposures');
This is too much data to query in production. You are only interested in the count of the exposure. Have a separate query to get that count.

2024-08-27 11:53 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/controllers/FeatureFlagController.ts
> +    const nodes = featureFlags.map((flag) => ({ ...flag, exposures: flag.featureFlagExposures.length }));
This transformation should be done inside the service itself.

2024-08-28 11:01 UTC, VivekFitkariwala submitted a review, later dismissed
Some types changes

2024-08-28 19:15 UTC, bcb37 commented on backend/packages/Upgrade/src/api/services/FeatureFlagService.ts
>    ): Promise<FeatureFlag[]> {
It looks like `loadRelationCountAndMap()` doesn't change the return type of `getMany()`. So even though the query returns the correct type, type assigned to the return value of `getMany()` is still the type of the model. It's possible to remedy this with a `@VirtualColumn` but that decorator is only available in version 0.3.11.

2024-08-29 05:28 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/services/FeatureFlagService.ts
>    ): Promise<FeatureFlag[]> {
Ohh I see it. Either we can 

1. Update the typeORM and fix this (This should be done as a separate PR)
2. Use type assertion and add a TODO

```
Promise<(Omit<FeatureFlag, 'featureFlagExposures'> & { featureFlagExposures: number })[]> // For function return

return queryBuilder.getMany() as unknown as (Omit<FeatureFlag, 'featureFlagExposures'> & { // For function return
      featureFlagExposures: number;
    })[];
```

3. ignore it for now and add TODO to add

2024-08-29 18:38 UTC, bcb37 commented on backend/packages/Upgrade/src/api/services/FeatureFlagService.ts
>    ): Promise<FeatureFlag[]> {
I choose 3

2024-08-30 08:02 UTC, VivekFitkariwala approved these changes

2024-08-30 17:47 UTC, merged