Add index to models
CarnegieLearningWeb/UpGrade pull request #1881
Opened 2024-08-29 07:20 UTC by VivekFitkariwala

The query shared by Kenneth has Joins over
`experiment_user`
`experiment`

![image](https://github.com/user-attachments/assets/93036ef9-dbfc-4848-977a-80a6a45665a8)

Adding the indexing should fix the problem.

This is a cherry-picked [commit](https://github.com/CarnegieLearningWeb/UpGrade/commit/58268e4c3d34e5a211352b750a792bae2d84283b) from the dev branch.

2024-08-29 20:03 UTC, bcb37 approved these changes

2024-08-29 20:14 UTC, bcb37 requested changes
We need to add the migration to the list in Typeormloader!

See, it's easy to forget, and I don't think it's necessary.

2024-08-30 14:26 UTC, VivekFitkariwala commented
@bcb37 I have pushed the fix

2024-08-30 16:21 UTC, bcb37 approved these changes

2024-08-30 17:49 UTC, merged