Display 'No matching feature flags found' message when no flags found from search
CarnegieLearningWeb/UpGrade pull request #1906
Opened 2024-09-06 05:05 UTC by zackcl

This PR displays the message "No matching feature flags found" on the Feature Flags Root Section Card Table instead of "No feature flags are defined. Create a new feature flag." when no matching feature flags are found from the search.

<img width="1000" alt="Screenshot 2024-09-06 at 2 02 22 PM" src="https://github.com/user-attachments/assets/93d7a0b0-910d-4bd5-89f2-e3371fb3be53">

2024-09-10 08:26 UTC, zackcl commented
@Yagnik56 @VivekFitkariwala Please review and approve this PR.

2024-09-10 08:30 UTC, zackcl commented
OK, I will first resolve conflicts.

2024-09-11 09:44 UTC, VivekFitkariwala commented on frontend/projects/upgrade/src/app/features/dashboard/feature-flags/pages/feature-flag-root-page/feature-flag-root-page-content/feature-flag-root-section-card/feature-flag-root-section-card.component.ts
> +    this.isSearchActive$ = of(!!params.searchString);
This is not needed

2024-09-11 09:46 UTC, VivekFitkariwala requested changes

2024-09-11 09:46 UTC, VivekFitkariwala commented on frontend/projects/upgrade/src/app/features/dashboard/feature-flags/pages/feature-flag-root-page/feature-flag-root-page-content/feature-flag-root-section-card/feature-flag-root-section-card.component.ts
> +  isSearchActive$ = of(false);
You should subscribe the value from the store.

2024-09-11 09:46 UTC, VivekFitkariwala commented on frontend/projects/upgrade/src/app/features/dashboard/feature-flags/pages/feature-flag-root-page/feature-flag-root-page-content/feature-flag-root-section-card/feature-flag-root-section-card.component.ts
> +    this.isSearchActive$ = of(!!params.searchString);
This is not needed

2024-09-11 09:46 UTC, VivekFitkariwala commented on frontend/projects/upgrade/src/app/features/dashboard/feature-flags/pages/feature-flag-root-page/feature-flag-root-page-content/feature-flag-root-section-card/feature-flag-root-section-card.component.ts
> +import { Observable, Subscription, map, of } from 'rxjs';
Remove Subscription

2024-09-11 13:09 UTC, zackcl commented
@VivekFitkariwala I resolved all your comments. Please feel free to approve this PR.

2024-09-11 13:40 UTC, VivekFitkariwala approved these changes

2024-09-11 14:15 UTC, merged