Enhancement: replace @CurrentUser user type with userDTO
CarnegieLearningWeb/UpGrade pull request #2061
Opened 2024-10-16 13:10 UTC by ppratikcr7

This resolves issue #1894

2024-10-17 12:52 UTC, VivekFitkariwala requested changes

2024-10-17 12:52 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/repositories/ExperimentAuditLogRepository.ts
> +    user: UserDTO,
This is incorrect. You will be saving User document in the database not the DTO

2024-10-17 12:52 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/controllers/UserController.ts
> +    @Body({ validate: true }) user: UserDTO, @Req() request: AppRequest): Promise<UserDTO> {
The return type should not be changed

2024-10-17 12:52 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/controllers/UserController.ts
> +  ): Promise<UserDTO> {
The return type should not be changed

2024-10-17 12:52 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/controllers/UserController.ts
> +  public delete(@Param('email') email: string): Promise<UserDTO> {
The return type should not be changed

2024-10-17 12:52 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/services/UserService.ts
> +  public async upsertUser(userDTO: UserDTO, logger: UpgradeLogger): Promise<UserDTO> {
The return type of the function is User

2024-10-17 12:52 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/services/UserService.ts
> +  public async updateUserDetails(firstName: string, lastName: string, email: string, role: UserRole): Promise<UserDTO> {
Same as above

2024-10-17 12:52 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/services/UserService.ts
> +  public deleteUser(email: string): Promise<UserDTO> {
Same as above

2024-10-17 12:58 UTC, ppratikcr7 commented
@VivekFitkariwala Okay, so a similar approach was being used earlier when the first ExperimentDTO was implemented by Ridham. Should I go ahead and update those return types and DB save types as well?

2024-10-17 13:00 UTC, VivekFitkariwala commented
@ppratikcr7, not in this PR, create a separate ticket.

2024-10-20 14:16 UTC, VivekFitkariwala approved these changes

2024-10-22 08:53 UTC, merged