hotfix to throw http 404 error for api calls other than init for new users
CarnegieLearningWeb/UpGrade pull request #2065
Opened 2024-10-17 12:28 UTC by ppratikcr7

This resolves an issue caught during QA of ticket #2045 where we got 404 httperror for hitting init api call for new users. This will filter the init api call to not throw 404 error on user not found.

2024-10-17 12:37 UTC, VivekFitkariwala requested changes

2024-10-17 12:37 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/services/ExperimentUserService.ts
> +    api?: string
This is not a good way. The function is doing more than what the name is suggesting.

2024-10-17 12:37 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/services/ExperimentUserService.ts
> -      throw new HttpError(404, `Experiment User not found: ${experimentUserId}`);
The error should not be thrown from here

2024-10-17 12:37 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/controllers/ExperimentClientController.v5.ts
> +    const experimentUserDoc = await this.experimentUserService.getUserDoc(experimentUser.id, request.logger, 'init');
Create a function in the controller which should return the experiment user doc if exist else should throw an error

2024-10-17 16:21 UTC, danoswaltCL commented
if this is a bugfix for release/6.0, it should be based from that

2024-10-22 08:27 UTC, ppratikcr7 commented
> if this is a bugfix for release/6.0, it should be based from that

No, this was an enhancement kind of ticket, which was intended for proper errors codes from api's. This was intended to go into dev.

2024-10-22 12:46 UTC, VivekFitkariwala approved these changes

2024-10-22 13:38 UTC, merged