Import feature flag list feature
CarnegieLearningWeb/UpGrade pull request #2071
Opened 2024-10-21 09:35 UTC by Yagnik56

This PR contains an import feature flag list feature with validation and import endpoints. 
![image](https://github.com/user-attachments/assets/e24a5bdd-1bbd-492c-ad10-25331043c443)
![image](https://github.com/user-attachments/assets/f242b384-d0bd-45e2-887d-9f36d76a0319)
![image](https://github.com/user-attachments/assets/80f57a42-055f-4bc0-b399-02deaf154ab8)

2024-10-21 15:23 UTC, zackcl commented on frontend/projects/upgrade/src/app/features/dashboard/feature-flags/pages/feature-flag-details-page/feature-flag-details-page-content/feature-flag-exclusions-section-card/feature-flag-exclusions-section-card.component.ts
>      console.log('Menu Button Item Clicked:', event);
Let's remove the logging which was added for testing.

2024-10-21 15:28 UTC, zackcl commented
@Yagnik56 Could you please share a working FF list JSON file (or content)?

2024-10-21 16:43 UTC, zackcl commented
Thanks for sharing the files. I tried importing the files you shared, but they all show up as "Incompatible."
<img width="1000" alt="Screenshot 2024-10-22 at 1 34 36 AM" src="https://github.com/user-attachments/assets/32d6a16f-dd21-49e0-87db-320eb87c7ea1">

Could it be because the file doesn't match the feature flag I'm trying to import it into?

```
{"createdAt":"2024-10-03T08:22:14.136Z","updatedAt":"2024-10-03T08:22:23.888Z","versionNumber":2,"segmentId":"306aeaac-0f58-4d28-8c6a-918430dc7218","featureFlagId":"ffb4b749-3127-44ff-9aae-e011dacbad73","enabled":true,"listType":"Individual","segment":{"createdAt":"2024-10-03T08:22:14.136Z","updatedAt":"2024-10-03T08:22:14.136Z","versionNumber":1,"id":"306aeaac-0f58-4d28-8c6a-918430dc7218","name":"bfdb","description":"","context":"mathia","type":"private","individualForSegment":[{"createdAt":"2024-10-03T08:22:23.888Z","updatedAt":"2024-10-03T08:22:23.888Z","versionNumber":1,"segmentId":"306aeaac-0f58-4d28-8c6a-918430dc7218","userId":"bfbfd"}],"groupForSegment":[],"subSegments":[]}}
```

By the way, I'm not sure why we need to include the feature-flag-specific properties in the List file. These files should be exported from and imported into different feature flags (Include and Exclude Lists) and segments (Lists) tables.

Could we simply include list-specific properties in the List file? I think the properties might differ depending on the "listType."

2024-10-21 16:55 UTC, Yagnik56 commented
The list's context and feature flag must match; all these lists have mathia as context. The feature flag ID isn't needed. It will be removed from export and where the list is getting imported that feature flag's ID will be added during import from the backend. For the listType segment, the subsegment it refers to should exist with the same context as the feature flag we are importing that list in. For a group, the group type has to be valid for its context.

2024-10-22 14:07 UTC, VivekFitkariwala requested changes

2024-10-22 14:07 UTC, VivekFitkariwala commented on frontend/projects/upgrade/src/app/shared/services/common-dialog.service.ts
> +    const commonModalConfig: CommonModalConfig<ImportListParams> = {
This can be refactored to be a common object

2024-10-23 14:46 UTC, zackcl commented
@Yagnik56 Could you please reshare a JSON file content with minimal information possible? I think you mentioned many of the properties (e.g., `featureFlagId`) won't be included in the JSON file when exported, right? It would be helpful to see the file content for discussion tomorrow (we could discuss whether we want to include the `context ` in the file or not).

2024-10-24 11:47 UTC, Yagnik56 commented
@zackcl I updated the `json` files in the description and removed the data that the backend won't send in export. You can have a look.

2024-10-24 12:04 UTC, zackcl commented
Here are the file contents for reference:
----------
Individual_list.json:
```
{
   "enabled":true,
   "listType":"Individual",
   "segment":{
      "name":"bfdb",
      "description":"",
      "context":"mathia",
      "type":"private",
      "individualForSegment":[
         {
            "createdAt":"2024-10-03T08:22:23.888Z",
            "updatedAt":"2024-10-03T08:22:23.888Z",
            "versionNumber":1,
            "segmentId":"306aeaac-0f58-4d28-8c6a-918430dc7218",
            "userId":"bfbfd"
         }
      ],
      "groupForSegment":[
         
      ],
      "subSegments":[
         
      ]
   }
}
```

Group_list.json:
```
{
   "enabled":false,
   "listType":"group1",
   "segment":{
      "name":"fbdfd",
      "description":"",
      "context":"mathia",
      "type":"private",
      "individualForSegment":[
         
      ],
      "groupForSegment":[
         {
            "createdAt":"2024-10-03T08:22:19.392Z",
            "updatedAt":"2024-10-03T08:22:19.392Z",
            "versionNumber":1,
            "segmentId":"1be939c9-afcb-49ac-bc77-28bf8fc2126f",
            "groupId":"fbdf",
            "type":"group1"
         }
      ],
      "subSegments":[
         
      ]
   }
}
```

Segment_list.json:

```
{
   "enabled":true,
   "listType":"Segment",
   "segment":{
      "name":"seg1",
      "description":"2",
      "context":"mathia",
      "type":"private",
      "individualForSegment":[
         
      ],
      "groupForSegment":[
         
      ],
      "subSegments":[
         {
            "createdAt":"2024-10-01T08:59:24.244Z",
            "updatedAt":"2024-10-01T09:10:14.316Z",
            "versionNumber":4,
            "id":"a78e3c7d-8d55-438a-afd3-c9539fbb870a",
            "name":"seg1",
            "description":"2",
            "context":"mathia",
            "type":"public"
         }
      ]
   }
}
```

2024-10-28 09:53 UTC, VivekFitkariwala requested changes
Small changes.

2024-10-28 09:53 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/services/FeatureFlagService.ts
> +        if (!featureFlag) {
Write a single if statement 
```suggestion
        if (!featureFlag || (!parsedFile.content))
```

2024-10-28 09:53 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/services/FeatureFlagService.ts
> +        const error = await this.validateImportFeatureFlagList(parsedFile.fileName, featureFlag, parsedFile.content);
Return the function itself

2024-10-28 09:53 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/services/FeatureFlagService.ts
> +        if (listType === FEATURE_FLAG_PARTICIPANT_LIST_KEY.INCLUDE) {
You don't need the if else case

2024-10-28 09:53 UTC, VivekFitkariwala commented on frontend/projects/upgrade/src/app/shared/services/common-dialog.service.ts
> +  ImportListParams,
Remove this

2024-10-28 09:53 UTC, VivekFitkariwala commented on frontend/projects/upgrade/src/app/shared/services/common-dialog.service.ts
> +  openImportModal(title, listType, flagId) {
Add types here

2024-10-30 11:08 UTC, VivekFitkariwala approved these changes

2024-11-05 13:34 UTC, VivekFitkariwala approved these changes

2024-11-05 14:32 UTC, merged