implemented signals for import-feature-flag
CarnegieLearningWeb/UpGrade pull request #2086
Opened 2024-10-30 04:50 UTC by RidhamShah

2024-11-05 14:50 UTC, VivekFitkariwala commented
@RidhamShah, I am not sure if I understood this PR. The goal was to move the component-specific state and dataService calls to the component store. There are two requests: validation and import. Both of these calls are not updating the main store as after the import, we are calling `this.featureFlagsService.fetchFeatureFlags(true);` to fetch all the feature flags. At the end of the PR, the component should not have `featureFlagsService` and `featureFlagsDataService`. The isLoadingImportFeatureFlag attribute in the feature flag model should also be removed.

2024-11-05 14:50 UTC, VivekFitkariwala requested changes

2024-11-22 09:02 UTC, RidhamShah commented on frontend/projects/upgrade/src/app/core/feature-flags/store/feature-flag.signal.store.ts
file moved

2024-11-26 05:07 UTC, RidhamShah commented on frontend/projects/upgrade/src/app/core/feature-flags/store/feature-flag.signal.store.ts
> +    super({ featureFlags: [], isLoading: false, importResults: [] });
code removed

2024-11-26 13:21 UTC, VivekFitkariwala requested changes
Small changes before I can approve this

2024-11-26 13:21 UTC, VivekFitkariwala commented on frontend/projects/upgrade/src/app/core/feature-flags/feature-flags.module.ts
This is not needed

2024-11-26 15:00 UTC, RidhamShah commented on frontend/projects/upgrade/src/app/shared/services/common-dialog.service.ts
> +  openImportModal(title: string, listType: FEATURE_FLAG_LIST_FILTER_MODE, flagId: string, modelType?: MODEL_TYPE) {
i was thinking that there may be other places where this function is used. As it is not, I will remove the optional part

2024-11-27 03:27 UTC, RidhamShah commented on frontend/projects/upgrade/src/app/core/feature-flags/feature-flags.module.ts
code removed

2025-03-06 13:37 UTC, danoswaltCL commented
closing the PR as we haven't had the capacity to try this idea out, I wish we could switch to this style because it looks good but would be hard to switch and maintain both styles

2025-03-06 13:37 UTC, closed without merging