Bugfix for experiment data export storing condition name in condition payload column
CarnegieLearningWeb/UpGrade pull request #2092
Opened 2024-11-04 12:38 UTC by ppratikcr7

This resolves ticket #2090

2024-11-04 13:23 UTC, VivekFitkariwala requested changes
Can you add proper types in the relevant code? This error came because in
`let experiment = acc.find((e) => e.experimentId === item.experimentId);` experiment is `any`

`let experiment` is `ExperimentCSVData` and the same variable is used for the experiment.

2024-11-04 14:41 UTC, danoswaltCL commented
@amurphy-cl should this go in the release?

2024-11-04 15:04 UTC, VivekFitkariwala requested changes

2024-11-04 16:34 UTC, danoswaltCL commented
I believe that @amurphy-cl said go ahead and put this into the release

2024-11-05 08:59 UTC, ppratikcr7 commented on backend/packages/Upgrade/src/api/services/AnalyticsService.ts
>        const formattedExperiments = experimentQueryResult.reduce((acc, item) => {
Yes, I will update the type to `ExperimentCSVData[]`. So, `experimentQueryResult` has the data row for each condition payload. We are getting the experiment generic data first and then we add the payload details in a separate key called `details`. Later we use this `formattedExperiments` to get the individual enrolment data for that experiment. So, its basically we are not checking for unique values but pushing all the condition payload details in the `formattedExperiments`. The naming is nit odd, will update them.

2024-11-06 14:15 UTC, ppratikcr7 commented
Closing this as its handled by a new [PR](https://github.com/CarnegieLearningWeb/UpGrade/pull/2095)

2024-11-06 14:15 UTC, closed without merging