adding session-id in logs and adding some logs
CarnegieLearningWeb/UpGrade pull request #238
Opened 2022-02-01 14:16 UTC by ppratikcr7

2022-02-03 11:43 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/services/ExperimentService.ts
> +    logger.info({ user: currentUser, message: 'Create a new experiment =>', details:  experiment.toString() });
Why not adding user in `logger.child`?

2022-02-03 12:11 UTC, ppratikcr7 commented on backend/packages/Upgrade/src/api/services/ExperimentService.ts
> +    logger.info({ user: currentUser, message: 'Create a new experiment =>', details:  experiment.toString() });
okay, will do that.

2022-02-28 08:38 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/middlewares/LogMiddleware.ts
> -      api_request_type: null,
`request_method_type: req.method`

2022-02-28 08:39 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/services/ExperimentService.ts
> +      logger.info({ message: `Update the experiment`, details: experiment.toString() });
use `details: experiment`

2022-02-28 08:42 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/api/services/ExperimentService.ts
> +        logger.info({message:'Updated experiment:', details: newExperiment.toString()})
remove `.toString`

2022-02-28 08:44 UTC, VivekFitkariwala commented on backend/packages/Upgrade/src/auth/authorizationChecker.ts
> +  const log = new UpgradeLogger();
Can we get logger instance from the request object here instead of creating our own logger?

2022-02-28 08:47 UTC, VivekFitkariwala requested changes
Please go through comments

2022-03-02 14:49 UTC, ppratikcr7 commented on backend/packages/Upgrade/src/api/middlewares/LogMiddleware.ts
> -      api_request_type: null,
done

2022-03-02 14:52 UTC, ppratikcr7 commented on backend/packages/Upgrade/src/api/services/ExperimentService.ts
> +        logger.info({message:'Updated experiment:', details: newExperiment.toString()})
done

2022-03-02 14:53 UTC, ppratikcr7 commented on backend/packages/Upgrade/src/api/services/ExperimentService.ts
> +      logger.info({ message: `Update the experiment`, details: experiment.toString() });
done

2022-03-03 06:04 UTC, VivekFitkariwala approved these changes

2022-03-03 06:10 UTC, merged