Removing swc compiler
CarnegieLearningWeb/UpGrade pull request #246
Opened 2022-02-03 20:22 UTC by VivekFitkariwala

Removed swc compiler
[swc](https://swc.rs/#overview) compiler support limited platform.

2022-02-04 12:51 UTC, mfugate1 requested changes

2022-02-04 12:51 UTC, mfugate1 commented on backend/Dockerfile
> +RUN apk add g++ make python
It's for the new relic native-metrics package, right? That error can actually be ignored. When it fails to build the dependency, it just downloads it instead.

You can get rid of those extra packages, and just add this environment variable instead to get rid of the error:
`ENV NR_NATIVE_METRICS_NO_BUILD=true`

2022-02-06 14:03 UTC, VivekFitkariwala commented on backend/Dockerfile
> +RUN apk add g++ make python
Yup this is for new relic native-metrics package.
Thanks for the above solution it worked.

2022-02-06 19:00 UTC, mfugate1 approved these changes

2022-02-07 06:17 UTC, ppratikcr7 approved these changes

2022-02-07 14:47 UTC, merged